version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - app
    volumes:
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./auth/.htpasswd:/etc/nginx/.htpasswd
